#!/usr/bin/env php
<?php



if(!$argv){
	die('no argv');
}

$_GET['route'] = $argv[1];

// Version
define('VERSION', '3.0.3.7');
define('VERSION_CORE', 'ocStore');
define('VERSION_BUILD', '0001');

// Configuration
if (is_file(__DIR__ . '/config.php')) {
	require_once(__DIR__ . '/config.php');
}

// Startup
require_once(DIR_SYSTEM . 'startup.php');

start('catalog');

?>
