#!/usr/bin/env php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$start_time = microtime(true);

if(!$argv){
	die('no argv');
}
$_GET['route'] = $_ARGV = $argv[1];
// Version
define('VERSION', '3.0.3.7');
define('VERSION_CORE', 'ocStore');
define('VERSION_BUILD', '0001');

// Configuration
if (is_file(__dir__ . '/config.php')) {
	require_once(__dir__ . '/config.php');
}

// Install
if (!defined('DIR_APPLICATION')) {
	exit;
}

// Startup
require_once(DIR_SYSTEM . 'startup.php');

start('admin');

?>